
import java.awt.Color;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fbtbr
 */
public class kayit extends javax.swing.JFrame {

    private final Color kremZemin = new Color(250, 245, 236);     
    private final Color koyuYesil = new Color(20, 51, 44);        
    private final Color altinBronz = new Color(191, 149, 80);     
    private final Color beyaz = Color.WHITE;                      
    private final Color yaziRengi = new Color(50, 50, 50);        
    private final Color GriKenarlik = new Color(220, 215, 205);
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(kayit.class.getName());

    /**
     * Creates new form kayit
     */
    private JTextField txtTc, txtIsim, txtSoyisim, txtTelefon, txtAdres, txtGmail;
    private JPasswordField txtSifre;
    private JButton btnKaydet;

    public kayit() {
        initComponents();
        kayitTasariminiYukle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
private void kayitTasariminiYukle() {
        setTitle("Leziz Lezzetler - Yeni Kayıt");
        setSize(500, 750); // Çok fazla veri olduğu için ekranı biraz uzattık
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        getContentPane().setBackground(kremZemin);
        setLayout(new GridBagLayout()); 

        // ANA KAYIT KARTI (Gölgeli ve yuvarlatılmış panel)
        JPanel cardPanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(getBackground());
                g2.fill(new RoundRectangle2D.Float(0, 0, getWidth(), getHeight(), 20, 20));
                g2.dispose();
            }
        };
        cardPanel.setOpaque(false);
        cardPanel.setBackground(beyaz);
        cardPanel.setLayout(new BoxLayout(cardPanel, BoxLayout.Y_AXIS));
        cardPanel.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(235, 230, 220), 1, true),
                BorderFactory.createEmptyBorder(25, 40, 25, 40) // İç boşluklar
        ));
        cardPanel.setPreferredSize(new Dimension(400, 680));

        // 1. BAŞLIK ALANI 
        JLabel titleLabel = new JLabel("Hoşgeldiniz");
        titleLabel.setFont(new Font("Serif", Font.ITALIC | Font.BOLD, 28)); 
        titleLabel.setForeground(koyuYesil);
        titleLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        JLabel subTitleLabel = new JLabel("Lezzet dünyasına adım atmak için bilgilerinizi girin");
        subTitleLabel.setFont(new Font("SansSerif", Font.PLAIN, 12));
        subTitleLabel.setForeground(altinBronz);
        subTitleLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        // KUTULARI OLUŞTURMA İŞLEMİ
        txtTc = new JTextField();
        txtIsim = new JTextField();
        txtSoyisim = new JTextField();
        txtTelefon = new JTextField();
        txtAdres = new JTextField();
        txtGmail = new JTextField();
        txtSifre = new JPasswordField();

        // 2. BUTONLAR
        JButton btnKaydet = new JButton("Kaydi Tamamla");
        btnKaydet.setMaximumSize(new Dimension(320, 42));
        btnKaydet.setBackground(koyuYesil);
        btnKaydet.setForeground(beyaz);
        btnKaydet.setFont(new Font("SansSerif", Font.BOLD, 14));
        btnKaydet.setAlignmentX(Component.CENTER_ALIGNMENT);
        btnKaydet.setFocusPainted(false);
        btnKaydet.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnKaydet.setBorder(BorderFactory.createEmptyBorder());

        JButton btnGeri = new JButton("Zaten hesabınız var mı? Giriş Yapın");
        btnGeri.setMaximumSize(new Dimension(320, 30));
        btnGeri.setForeground(altinBronz);
        btnGeri.setFont(new Font("SansSerif", Font.BOLD, 12));
        btnGeri.setAlignmentX(Component.CENTER_ALIGNMENT);
        btnGeri.setContentAreaFilled(false); 
        btnGeri.setBorderPainted(false);
        btnGeri.setFocusPainted(false);
        btnGeri.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // BİLEŞENLERİ KARTA YERLEŞTİRME (Yardımcı metod ile hızlıca ekliyoruz)
        cardPanel.add(titleLabel);
        cardPanel.add(Box.createRigidArea(new Dimension(0, 5)));
        cardPanel.add(subTitleLabel);
        cardPanel.add(Box.createRigidArea(new Dimension(0, 20))); 
        
        alaniEkle(cardPanel, "TC Kimlik No", txtTc);
        alaniEkle(cardPanel, "İsim", txtIsim);
        alaniEkle(cardPanel, "Soyisim", txtSoyisim);
        alaniEkle(cardPanel, "Telefon", txtTelefon);
        alaniEkle(cardPanel, "Adres", txtAdres);
        alaniEkle(cardPanel, "E-Posta (Gmail)", txtGmail);
        alaniEkle(cardPanel, "Şifre", txtSifre);
        
        cardPanel.add(Box.createRigidArea(new Dimension(0, 10)));
        cardPanel.add(btnKaydet);
        cardPanel.add(Box.createRigidArea(new Dimension(0, 10)));
        cardPanel.add(btnGeri);

        
        btnGeri.addActionListener(e -> {
            kayit.this.dispose();
            new LoginScreen().setVisible(true);
        });

        // --- KAYIT OL BUTONU MOTORU ---
        btnKaydet.addActionListener(e -> {
            String url = "jdbc:mysql://localhost:3306/siparisrandevudb";
            String user = "root";
            String password = "";

            try {
                Connection conn = DriverManager.getConnection(url, user, password);
                
                // SQL Sorgumuz (Dünkü tc_no düzeltmesi ile)
                String sql = "INSERT INTO kullanicilar (tc_no, isim, soyisim, telefon, adres, gmail, sifre) VALUES (?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement pstmt = conn.prepareStatement(sql);

                // 7 Soruluk koltukları sırayla dolduruyoruz
                pstmt.setString(1, txtTc.getText());
                pstmt.setString(2, txtIsim.getText());
                pstmt.setString(3, txtSoyisim.getText());
                pstmt.setString(4, txtTelefon.getText());
                pstmt.setString(5, txtAdres.getText());
                pstmt.setString(6, txtGmail.getText());
                pstmt.setString(7, new String(txtSifre.getPassword()));

                int eklenenSatir = pstmt.executeUpdate();

                if (eklenenSatir > 0) {
                    JOptionPane.showMessageDialog(null, "Kayıt Başarılı! Aramıza hoş geldin " + txtIsim.getText() + ".");
                    
                    // Kayıt başarılı olunca otomatik olarak giriş ekranına atar
                    kayit.this.dispose();
                    new LoginScreen().setVisible(true); 
                }

                pstmt.close();
                conn.close();
            } catch (Exception ex) {
                // Eğer aynı Gmail ile kayıt olunmaya çalışılırsa burası hatayı yakalar
                JOptionPane.showMessageDialog(null, "Kayıt Hatası: " + ex.getMessage());
            }
        });

        add(cardPanel);
    }
private void alaniEkle(JPanel panel, String baslik, JTextField kutu) {
        JLabel etiket = new JLabel(baslik);
        etiket.setFont(new Font("SansSerif", Font.BOLD, 11));
        etiket.setForeground(yaziRengi);
        etiket.setAlignmentX(Component.CENTER_ALIGNMENT);
        
        kutuyuModernlestir(kutu);
        
        panel.add(etiket);
        panel.add(Box.createRigidArea(new Dimension(0, 4)));
        panel.add(kutu);
        panel.add(Box.createRigidArea(new Dimension(0, 12))); // Kutular arası boşluk
    }
private void kutuyuModernlestir(JTextField field) {
        field.setMaximumSize(new Dimension(320, 32));
        field.setFont(new Font("SansSerif", Font.PLAIN, 13));
        field.setBackground(new Color(248, 248, 246)); 
        field.setForeground(yaziRengi);
        field.setCaretColor(koyuYesil);
        field.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(GriKenarlik, 1, true),
                BorderFactory.createEmptyBorder(2, 8, 2, 8) 
        ));
    }
public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatLightLaf());
        } catch (Exception ex) {
            try { UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName()); } catch(Exception e){}
        }
        java.awt.EventQueue.invokeLater(() -> new kayit().setVisible(true));
    }

}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

