
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;



public class LoginScreen extends javax.swing.JFrame {
    //renk kodları bütün sayfalarda mevcuttur
    private final Color kremZemin = new Color(250, 245, 236);
    private final Color koyuYesil = new Color(20, 51, 44);
    private final Color altinBronz = new Color(191, 149, 80);
    private final Color beyaz = Color.WHITE;
    private final Color yaziRengi = new Color(50, 50, 50);
    private final Color GriKenarlik = new Color(220, 215, 205);
    private JTextField emailField;//mail ve şifreyi almak için oluşturduğumuz yapılar
    private JPasswordField passwordField;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginScreen.class.getName());

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();

        girisTasariminiYukle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // FlatLaf modern temasını devreye alıyoruz (Böylece unused import uyarısı kaybolacak)
            javax.swing.UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatLightLaf());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Formu ekranda göster */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginScreen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
  private void girisTasariminiYukle() {
        //title üst kısımdaki çubukta bulunan yazıalr
        setTitle("Leziz Lezzetler - Hoş Geldiniz");
        setSize(480, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        getContentPane().setBackground(kremZemin);
        setLayout(new GridBagLayout());

        // container gibi kullandığımız card panel üstünde bütün herşeyi barındıran yer
        JPanel cardPanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(getBackground());
                g2.fill(new RoundRectangle2D.Float(0, 0, getWidth(), getHeight(), 20, 20));
                g2.dispose();
            }
        };
        cardPanel.setOpaque(false);
        cardPanel.setBackground(beyaz);
        cardPanel.setLayout(new BoxLayout(cardPanel, BoxLayout.Y_AXIS));
        cardPanel.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(235, 230, 220), 1, true),
                BorderFactory.createEmptyBorder(35, 40, 35, 40)
        ));
        cardPanel.setPreferredSize(new Dimension(380, 480));

        // 1. BAŞLIK ALANI 
        JLabel titleLabel = new JLabel("Leziz Lezzetler");//üst tarafta bulunan Logo
        titleLabel.setFont(new Font("Serif", Font.ITALIC | Font.BOLD, 32));
        titleLabel.setForeground(koyuYesil);
        titleLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        JLabel subTitleLabel = new JLabel("");
        subTitleLabel.setFont(new Font("SansSerif", Font.PLAIN, 13));
        subTitleLabel.setForeground(altinBronz);
        subTitleLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        // mailin alındığı yer
        JLabel emailLabel = new JLabel("E-Posta Adresiniz");
        emailLabel.setFont(new Font("SansSerif", Font.BOLD, 12));
        emailLabel.setForeground(yaziRengi);
        emailLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        emailField = new JTextField() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                if (getText().isEmpty() && !hasFocus()) {
                    Graphics2D g2 = (Graphics2D) g.create();
                    g2.setColor(Color.LIGHT_GRAY);
                    g2.setFont(getFont().deriveFont(Font.ITALIC));
                    g2.drawString("fatih1234@gmail.com", 10, 22);//burada textfield ın içinde bulunan gri kısım için olan kodlar bulunuyor
                    g2.dispose();
                }
            }
        };
        kutuyuModernlestir(emailField);//textfieldı düzeltiyoruz

        // şifrenin alındığı textfield burdan alınıyor
        JLabel passwordLabel = new JLabel("Şifreniz");
        passwordLabel.setFont(new Font("SansSerif", Font.BOLD, 12));
        passwordLabel.setForeground(yaziRengi);
        passwordLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        passwordField = new JPasswordField();
        kutuyuModernlestir(passwordField);

        // giriş yap butonu
        JButton loginButton = new JButton("Giriş Yap");
        loginButton.setMaximumSize(new Dimension(300, 42));
        loginButton.setBackground(koyuYesil);
        loginButton.setForeground(beyaz);
        loginButton.setFont(new Font("SansSerif", Font.BOLD, 14));
        loginButton.setAlignmentX(Component.CENTER_ALIGNMENT);
        loginButton.setFocusPainted(false);
        loginButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        loginButton.setBorder(BorderFactory.createEmptyBorder());

        // KAYIT OL BUTONU 
        JButton registerButton = new JButton("Hesabınız yok mu? Kayıt Olun");
        registerButton.setMaximumSize(new Dimension(300, 30));
        registerButton.setForeground(altinBronz);
        registerButton.setFont(new Font("SansSerif", Font.BOLD, 12));
        registerButton.setAlignmentX(Component.CENTER_ALIGNMENT);
        registerButton.setContentAreaFilled(false);
        registerButton.setBorderPainted(false);
        registerButton.setFocusPainted(false);
        registerButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // BİLEŞENLERİ KARTA YERLEŞTİRME 
        cardPanel.add(titleLabel);
        cardPanel.add(Box.createRigidArea(new Dimension(0, 5)));
        cardPanel.add(subTitleLabel);
        cardPanel.add(Box.createRigidArea(new Dimension(0, 35)));

        cardPanel.add(emailLabel);
        cardPanel.add(Box.createRigidArea(new Dimension(0, 8)));
        cardPanel.add(emailField);
        cardPanel.add(Box.createRigidArea(new Dimension(0, 20)));

        cardPanel.add(passwordLabel);
        cardPanel.add(Box.createRigidArea(new Dimension(0, 8)));
        cardPanel.add(passwordField);
        cardPanel.add(Box.createRigidArea(new Dimension(0, 35)));

        cardPanel.add(loginButton);
        cardPanel.add(Box.createRigidArea(new Dimension(0, 15)));
        cardPanel.add(registerButton);
// --- AKSİYONLAR BUTONLARA CAN VEREN KISIM ---
        registerButton.addActionListener(e -> {
            LoginScreen.this.dispose();
            new kayit().setVisible(true);
        });

        loginButton.addActionListener(e -> {
            String girilenEmail = emailField.getText();
            String girilenSifre = new String(passwordField.getPassword());

            // 1. ADIM: admin kontrolü eğer bu e postaya sahip biri girişi yaparsa direkt olarak admin paneline yönlendirilecek
            if (girilenEmail.equals("fatih@gmail.com") && girilenSifre.equals("1234")) {
                JOptionPane.showMessageDialog(null, "Hoşgeldiniz Sayın Yönetici.");

                // Admin sayfasını oluşturduğunda bu iki satırın başındaki // işaretlerini sil
                LoginScreen.this.dispose();
                new Admin_Paneli().setVisible(true);
                return;
            }

            // 2. ADIM: MÜŞTERİ KONTROLÜ Veritabanı
            String url = "jdbc:mysql://localhost:3306/siparisrandevudb";//mysql ile oluşturduğumuz siparisrandevudb 
            String user = "root";//burda mysql e giriş yapmak için kullandığımız şifre vve isim var
            String password = "";

            try {
                Connection conn = DriverManager.getConnection(url, user, password);

                String sql = "SELECT * FROM kullanicilar WHERE gmail = ? AND sifre = ?";//sql de gmail ve şifrelere bakıyoruz
                PreparedStatement pstmt = conn.prepareStatement(sql);//aldığımız gmail ve şifreyi sayısal değere dönüştürüyoruz gmail 1 şifre 2

                pstmt.setString(1, girilenEmail);//burda değişkemizle karşılaştırıyoruz
                pstmt.setString(2, girilenSifre);

                ResultSet rs = pstmt.executeQuery();//sq lsorgusunu çalışmasını sağlıyor

                if (rs.next()) {
                    String gelenIsim = rs.getString("isim");//giriş yapabildiyse hoşgeldin + kullanıcın ismi yalzıacak
                    JOptionPane.showMessageDialog(null, "Giriş Başarılı! Hoşgeldin " + gelenIsim);
                    Oturum.aktifKullaniciId = rs.getInt("Kullanici_id");//id yi de çekiyoruz diğer işlemlerde işimizde oldukça falza yarayacak

                    LoginScreen.this.dispose();
                    new Anasayfa().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Hatalı Giriş! E-posta adresiniz veya şifreniz yanlış.");//girilen bilgiler yanlışsa hata vercektir
                }

                rs.close();//bağlantı kesiliyor
                pstmt.close();
                conn.close();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Veritabanı Hatası: " + ex.getMessage());//eğerki bağlantı hiç sağlanamadıysa bu satır çalışır
            }
        });
        add(cardPanel);
    }

    // Giriş kutularını modernleştiren yardımcı metot
    private void kutuyuModernlestir(JTextField field) {
        field.setMaximumSize(new Dimension(300, 35));
        field.setFont(new Font("SansSerif", Font.PLAIN, 14));
        field.setBackground(new Color(248, 248, 246));
        field.setForeground(yaziRengi);
        field.setCaretColor(koyuYesil);
        field.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(GriKenarlik, 1, true),
                BorderFactory.createEmptyBorder(5, 10, 5, 10)
        ));
    }
}
